[@ww.select cssClass="builderSelectWidget" labelKey='xmppinteroptesting.executable.name' name='sintexecutable' list=uiConfigSupport.getExecutableLabels('sintexecutable') required='true' /]
[@ww.select cssClass="jdkSelectWidget" labelKey='builder.common.jdk' name='buildJdk' list=uiConfigSupport.jdkLabels required='true' /]
[@ww.textfield labelKey="xmppinteroptesting.host" name="host" required='true'/]
[@ww.textfield labelKey="xmppinteroptesting.domain" name="domain" required='true'/]
[@ww.textfield labelKey="xmppinteroptesting.timeout" name="timeout" required='true'/]
[@ww.textfield labelKey="xmppinteroptesting.adminAccountUsername" name="adminAccountUsername" required='false'/]
[@ww.password labelKey="xmppinteroptesting.adminAccountPassword" name="adminAccountPassword" required='false'/]
[@ww.textfield labelKey="xmppinteroptesting.enabledTests" name="enabledTests" required='false'/]
[@ww.textfield labelKey="xmppinteroptesting.enabledSpecifications" name="enabledSpecifications" required='false'/]
[@ww.textfield labelKey="xmppinteroptesting.disabledTests" name="disabledTests" required='false'/]
[@ww.textfield labelKey="xmppinteroptesting.disabledSpecifications" name="disabledSpecifications" required='false'/]
