name: Build

on: [pull_request]

permissions:
  checks: write

jobs:
  build-java:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
        distribution: [ temurin ] # We could add more here: temurin, adopt, liberica, microsoft, corretto
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven
      - name: Install Atlassian SDK
        run: |
          wget -q https://maven.artifacts.atlassian.com/com/atlassian/amps/atlassian-plugin-sdk/9.1.1/atlassian-plugin-sdk-9.1.1.tar.gz
          tar -xzf atlassian-plugin-sdk-9.1.1.tar.gz
          ./atlassian-plugin-sdk-9.1.1/bin/atlas-version
      - name: Build with Maven
        run: ./atlassian-plugin-sdk-9.1.1/apache-maven-3.9.8/bin/mvn --update-snapshots package
      - name: Stash the built artifacts
        uses: actions/upload-artifact@v4
        if: ${{ matrix.java == 8}}
        with:
          name: bamboo-plugin
          path: target/*.jar
